### ISSUE TITLE
İmport R

### ISSUE THREAD

**Issue by Ryuk-C** [nwagu/multiple-app-modules#2]
I want to copy a module to another module to create 2 apps. When I run the second module com.example.one.app R gives a problem. Make fixeswo.app.R by typing the package name of the second module as com.example.t. I need to do this for all files one by one. How do I prevent this?

**Comment by nwagu** [comment]
Please check this commit

https://github.com/nwagu/multiple-app-modules/commit/55efedf58ccac91c412cf299ee78b274e8b21811

The manifest of the shadow module should have the package name of the second app

**Comment by Ryuk-C** [comment]
The problem is solved, thank you very much.
