### ISSUE TITLE
Build Grade sourceSets

### ISSUE THREAD

**Issue by Ryuk-C** [nwagu/multiple-app-modules#3]
Hello. I want srcDir to copy only layout folder in Res folder. I don't want mipmap to be drawable and copyable. How can I do that?

    sourceSets {
        main {
            java {
                srcDir '../side-app/src/main/java'
            }
            assets {
                srcDir '../side-app/src/main/assets'
            }
            res {
                srcDirs '../side-app/src/main/res'
            }
        }
    }

**Comment by nwagu** [comment]
You can `exclude` the folders you don't want as part of your source

I will close this now since it is outside the scope of this project's aim.
